name: 'Deploy to AWS S3'
description: 'Deploy something to AWS S3'
inputs:
    bucket:
        description: 'S3 Bucket Name'
        required: true
    bucket-region:
        description: Region of AWS
        required: false
        default: 'us-east-1'
    dist-folder:
        description: 'The folder containing the deployable files'
        required: true

runs:
    using: 'node16'
    main: 'main.js'