name: "setup java"
description: "Download code and prepare java version"
inputs:
    java-version:
        description: "Java version"
        required: true
        default: "17"
runs:
    using: "composite"
    steps:
        -   name: Setup java with maven
            uses: actions/setup-java@v3
            with:
                distribution: 'zulu'
                java-version: ${{ inputs.java-version }}
                cache: 'maven'