name: build-with-maven
on: [workflow_dispatch, push]
jobs:
    generate-jar:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                  distribution: 'zulu'
                  java-version: '17'
                  cache: 'maven'
            - name: Build with Maven
              run: mvn -B package -DskipTests --file pom.xml
    unit-test:
        #needs: generate-jar
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/setup-java@v3
                with:
                    distribution: 'zulu'
                    java-version: '17'
                    cache: 'maven'
            -   name: Execute Unit Tests
                run: mvn -B test