name: build-with-maven
on:
    workflow_dispatch:
    pull_request:
        branches: [main]
    push:
        branches:
            - main
jobs:
    generate-jar:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                  distribution: 'zulu'
                  java-version: '17'
                  cache: 'maven'
            - name: Build with Maven
              run: mvn -B package -DskipTests --file pom.xml
            - name: Upload Jar
              uses: actions/upload-artifact@v3
              with:
                  name: app.jar
                  path: target/*.jar

    unit-test:
        needs: generate-jar
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/setup-java@v3
                with:
                    distribution: 'zulu'
                    java-version: '17'
                    cache: 'maven'
            -   name: Unit Tests
                run: mvn clean -B test

    integration-test:
        needs: generate-jar
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/setup-java@v3
                with:
                    distribution: 'zulu'
                    java-version: '17'
                    cache: 'maven'
            -   name: Integration Tests
                run: mvn clean -B integration-test

    deploy:
        needs: integration-test
        runs-on: ubuntu-latest
        steps:
            - name: Get Build Artifacts
              uses: actions/download-artifact@v3
              with:
                  name: app.jar
            - name: deploy into server
              #run: echo "Jar will be deployed later on"
              run: java -jar app.jar