name: build-with-maven
on:
    workflow_dispatch:
    pull_request:
        branches: [main]
    push:
        branches:
            - main
env:
    GLOBAL_TEST: Global ENV
jobs:
    generate-jar:
        runs-on: ubuntu-latest
        outputs:
            script-file: ${{steps.publish_name.outputs.script-file}}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                  distribution: 'zulu'
                  java-version: '17'
                  cache: 'maven'

            - name: Build with Maven
              run: mvn -B package -DskipTests --file pom.xml

            - name: Retrieve the jar file name
              id: publish_name
              run: |
                  find target/*.jar -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'

            - name: Upload Jar
              uses: actions/upload-artifact@v3
              with:
                  name: app.jar
                  path: target/*.jar

    unit-test:
        env:
            UNIT_TEST: Unit test ENV
        needs: generate-jar
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/setup-java@v3
                with:
                    distribution: 'zulu'
                    java-version: '17'
                    cache: 'maven'
            -   name: Unit Tests
                run: mvn clean -B test

    integration-test:
        env:
            INTEGRATION_TEST: Integration test ENV
        needs: generate-jar
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/setup-java@v3
                with:
                    distribution: 'zulu'
                    java-version: '17'
                    cache: 'maven'
            -   name: Integration Tests
                run: mvn clean -B -DskipTests integration-test

    deploy:
        needs: [integration-test, generate-jar]
        runs-on: ubuntu-latest
        steps:
            - name: Get Build Artifacts
              uses: actions/download-artifact@v3
              with:
                  name: app.jar

            - name: Output filename
              run: echo "${{needs.generate-jar.outputs.script-file}}"

            - name: deploy into server
              run: |
                  echo "Jar will be deployed later on"
