name: deploy
on: workflow_call
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Get Build Artifacts
              uses: actions/download-artifact@v3
              with:
                  name: app.jar
            - name: deploy into server
              run: echo "Jar will be deployed later on"