name: deploy
on: workflow_call
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: deploy into server
              run: |
                  echo "Jar will be deployed later on"