name: deploy
on:
    workflow_call:
        inputs:
            deployable-jar:
                description: jar to be deployed
                required: true
                type: string
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Get Artifact
              uses: actions/download-artifact@v3
              with:
                  name: ${{inputs.deployable-jar}}

            - name: deploy into server
              run: echo "Jar will be deployed later on"